- hosts: "{{ hosts }}"
  gather_facts: no
  become: yes
  serial: 1
  tasks:

    - name:  sync  to the destination
      synchronize:
        src: "{{ deploy_src_path }}"
        dest: "{{ deploy_dest_path }}"
        delete: "{{ delete_enable }}"
        rsync_opts: "{{ rsync_opts }}"
      tags: common

    - name: change dir owner
      file:
        path: "{{ deploy_dest_path }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        recurse: yes
      tags: dir_change_owner

    - name: change file owner
      file:
        path: "{{ deploy_dest_path }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
      tags: file_change_owner
