- hosts: "{{ hosts }}"
  gather_facts: no
  serial: "{{ Serial }}"
  tasks:
    - name: change local dir owner
      file:
        path: "{{ deploy_src_path }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        recurse: yes
      delegate_to: 127.0.0.1
      tags: local_change_owner

    - name:  sync  to the destination
      synchronize:
        src: "{{ deploy_src_path }}"
        dest: "{{ deploy_dest_path }}"
        delete: "{{ delete_enable }}"
        rsync_opts: "{{ rsync_opts }}"
      tags: common

    - name: change dest dir owner
      file:
        path: "{{ deploy_dest_path }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        recurse: yes
      tags: dir_change_owner

    - name: change dest file owner
      file:
        path: "{{ deploy_dest_path }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
      tags: file_change_owner
