- hosts: "{{ hosts }}"
  gather_facts: no
  serial: "{{ Serial }}"
  tasks:
    - name: Step:1/10:Download docker image.TaskId:"{{ TaskId }}".
      command: docker pull "{{ DockerImageURL }}{{ DockerApp }}:{{ DockerImageTag }}"
    - name: Step:2/10:Get the DockerAppId which is running. TaskId:"{{ TaskId }}".
      shell: docker ps|egrep '{{ DockerApp }}(\ |:|-20)'|awk '{print $1}'
      register: DockerAppId
    - name: Step:3/10:Get the AppInstance ID(e.host:port) from eureka. TaskId:"{{ TaskId }}".
      shell: curl -s "{{ EurekaUrl }}" |grep `hostname`:"{{ AppSpringName }}:" |awk -F / '{print $3}'
      register: AppInstance
    - name: Step:4/10:Deregister service.TaskId:"{{ TaskId }}".
      shell: curl  -s --max-time 3 http://"{{ AppInstance.stdout }}"/health/deregister
    - name: Step:5/10:Securyty wait times for eureka server&client cache refresh (default 60s).TaskId:"{{ TaskId }}".
      command: sleep "{{ WaitTimes }}"
    - name: Step:6/10:Shutdown service.TaskId:"{{ TaskId }}".
      shell: curl  -d '' http://"{{ AppInstance.stdout }}"/shutdown
    - name: Step:7/10:Securyty wait times for shutdown finished (default 60s).TaskId:"{{ TaskId }}".
      command: sleep "{{ WaitTimes }}"
    - name: Step:8/10:Docker app stop. TaskId:"{{ TaskId }}".
      command: docker stop "{{ DockerAppId.stdout }}"
      register: msg2
      failed_when: "'FAILED' in msg2.stderr"  
    - name: Step:9/10:Docker app run.TaskId:"{{ TaskId }}".
      command: "{{ DockerRun }}"
    - name: Step:10/10:LoopHealthCheck until successful, the default max time is 2min.TaskId:"{{ TaskId }}".
      script: sc_eureka_health_check.sh "{{ EurekaUrl }}" "{{ AppSpringName }}" "{{ MaxCheckTime }}"



