- hosts: "{{ hosts }}"
  gather_facts: no
  serial: "{{ Serial }}"
  tasks:
    - name:  step:1/4:Get the DockerAppId which is running. TaskId:"{{ TaskId }}".
      shell: docker ps|egrep '{{ DockerApp }}(\ |:|-20)'|awk '{print $1}'
      register: DockerAppId
    - name: step:2/4:Docker app stop. TaskId:"{{ TaskId }}".
      command: docker stop "{{ DockerAppId.stdout }}"
      register: msg2
      failed_when: "'FAILED' in msg2.stderr"
    - name:  step:3/4:Docker app start.TaskId:"{{ TaskId }}".
      command: docker start "{{ DockerAppId.stdout }}"
    - name:  Step:4/4:LoopHealthCheck until successful, the default max time is 2min.TaskId:"{{ TaskId }}".
      script: sc_health_check.sh "{{ ServicePort }}" "{{ HealthCheckUrl }}" "{{ MaxCheckTime }}"  
      tags: healthcheck



